version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dfxd3auxa3a5"
s3_prefix = "cloud-resume-challenge"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
